/* landing_label_gate.js — L-CASCADE-9 gate (S241).
 *
 * The newsroom landing carries two DATE LABELS that are plain hardcoded HTML:
 *   .week-meta   "Updated <date>"  above the 3-card row
 *   .feed-month  "<Month> <Year>"  dividers inside .feed-list
 *
 * Until v48.321 neither was regenerated by cascade_rebuild.js, so both drifted
 * silently on every drop while the six-surface cascade gate passed clean.
 * .week-meta sat at "Updated 19 June 2026" for six weeks; .feed-month read
 * "June 2026" over a run of rows dated 29-30 July 2026.
 *
 * This gate re-derives both from the NEWS array and fails loudly on drift.
 *
 * Usage:  node tools/landing_label_gate.js newsroom/index.html
 * Exit:   0 = PASS, 1 = FAIL
 */
const fs = require("fs");
const FILE = process.argv[2] || "newsroom/index.html";
const s = fs.readFileSync(FILE, "utf8");

const MON = ["January","February","March","April","May","June","July",
             "August","September","October","November","December"];
const dFull  = iso => { const [y,m,d] = iso.split("-").map(Number); return d + " " + MON[m-1] + " " + y; };
const dMonth = iso => { const [y,m]   = iso.split("-").map(Number); return MON[m-1] + " " + y; };
const mKey   = iso => String(iso).slice(0, 7);

// ---- parse NEWS (string-aware bracket match) ----
function parseNews(str) {
  const head = str.indexOf("var NEWS=");
  if (head < 0) throw new Error("NEWS array not found");
  const lb = str.indexOf("[", head);
  let d = 0, j = lb, inStr = false, q = "", esc = false;
  for (; j < str.length; j++) {
    const c = str[j];
    if (inStr) {
      if (esc) esc = false;
      else if (c === "\\") esc = true;
      else if (c === q) inStr = false;
      continue;
    }
    if (c === '"' || c === "'") { inStr = true; q = c; continue; }
    if (c === "[") d++;
    else if (c === "]") { d--; if (d === 0) break; }
  }
  return eval(str.slice(lb, j + 1));
}

const NEWS = parseNews(s);
const byId = Object.fromEntries(NEWS.map(x => [x.id, x]));

const failures = [];
const note = m => console.log("  " + m);

// ---- hero id (first data-article-id on the page) ----
const heroMatch = s.match(/data-article-id="(\d+)"/);
if (!heroMatch) { console.error("FAIL: no data-article-id found"); process.exit(1); }
const heroId = parseInt(heroMatch[1], 10);
const hero = byId[heroId];
if (!hero) { console.error("FAIL: hero id " + heroId + " not in NEWS"); process.exit(1); }

// ---- NR_STATIC_IDS ----
const sidMatch = s.match(/var NR_STATIC_IDS\s*=\s*\[([0-9,\s]*)\]/);
if (!sidMatch) { console.error("FAIL: NR_STATIC_IDS not found"); process.exit(1); }
const STATIC = sidMatch[1].split(",").map(t => parseInt(t.trim(), 10)).filter(n => !isNaN(n));
const feedIds = STATIC.slice(3); // [0..2] are the 3 cards, [3..9] are the 7 feed rows

console.log("=== landing label gate: " + FILE + " ===");
console.log("hero id " + heroId + " (" + hero.date + ") · feed ids " + feedIds.join(",") + "\n");

// ---- CHECK 1: .week-meta == hero release date ----
const wm = s.match(/<div class="week-meta">([^<]*)<\/div>/);
if (!wm) {
  failures.push("week-meta div not found");
} else {
  const want = "Updated " + dFull(hero.date);
  if (wm[1].trim() !== want) {
    failures.push('week-meta is "' + wm[1].trim() + '" but hero id ' + heroId +
                  " is dated " + hero.date + ' -> expected "' + want + '"');
  } else {
    note('week-meta  OK  "' + want + '"');
  }
}

// ---- CHECK 2: .feed-month dividers match the static feed run ----
const fl = s.indexOf('<div class="feed-list">');
if (fl < 0) {
  failures.push("feed-list not found");
} else {
  const region = s.slice(fl);
  const seq = [];
  const re = /<div class="feed-month">([^<]*)<\/div>|<a class="feed-row"[^>]*data-article-id="(\d+)"/g;
  let m, seen = 0;
  while ((m = re.exec(region)) && seen < feedIds.length) {
    if (m[1] !== undefined) seq.push({ divider: m[1].trim() });
    else { seq.push({ row: parseInt(m[2], 10) }); seen++; }
  }

  // expected: divider at each month boundary across feedIds, in order
  const expected = [];
  let last = null;
  for (const id of feedIds) {
    const x = byId[id];
    if (!x) { failures.push("feed id " + id + " not in NEWS"); continue; }
    const k = mKey(x.date);
    if (k !== last) { expected.push({ divider: dMonth(x.date) }); last = k; }
    expected.push({ row: id });
  }

  const fmt = a => a.map(e => e.divider !== undefined ? "[" + e.divider + "]" : String(e.row)).join(" ");
  if (fmt(seq) !== fmt(expected)) {
    failures.push("feed-month sequence drift\n      actual   " + fmt(seq) +
                  "\n      expected " + fmt(expected));
  } else {
    note("feed-month OK  " + fmt(expected));
  }
}

console.log("");
if (failures.length) {
  console.error("FAIL (" + failures.length + "):");
  failures.forEach(f => console.error("  - " + f));
  process.exit(1);
}
console.log("CLEAN: both landing date labels agree with NEWS.");
